# Generated by Django 3.1 on 2020-08-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_id', models.SlugField(max_length=100)),
                ('url', models.URLField(max_length=150)),
                ('embed_url', models.URLField(max_length=150)),
                ('broadcaster_id', models.PositiveIntegerField()),
                ('broadcaster_name', models.SlugField(max_length=30)),
                ('creator_id', models.PositiveIntegerField()),
                ('creator_name', models.SlugField(max_length=30)),
                ('video_id', models.PositiveIntegerField()),
                ('game_id', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=150)),
                ('view_count', models.PositiveIntegerField()),
                ('created_at', models.DateField()),
                ('thumbnail_url', models.URLField(max_length=150)),
            ],
        ),
    ]
