# Generated by Django 3.1 on 2020-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clip',
            name='video_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
