# Generated by Django 3.1 on 2020-08-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0003_auto_20200812_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='video_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
