# Generated by Django 3.1 on 2020-08-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0004_auto_20200812_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='video_id',
        ),
    ]
