# Generated by Django 3.1 on 2020-08-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_remove_clip_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
            ],
        ),
    ]
