# Generated by Django 3.1 on 2020-08-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0008_game_box_art_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='saved_offline',
            field=models.BooleanField(default=False),
        ),
    ]
