# Generated by Django 3.1 on 2020-08-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0009_clip_saved_offline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clip',
            old_name='saved_offline',
            new_name='archived',
        ),
    ]
