# Generated by Django 3.1 on 2020-08-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0010_auto_20200813_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcaster_name', models.SlugField(max_length=30)),
                ('broadcaster_id', models.PositiveIntegerField()),
                ('bearer', models.SlugField()),
                ('client_id', models.SlugField()),
            ],
        ),
    ]
