# Generated by Django 3.1 on 2020-08-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0011_twitchsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchsettings',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
