# Generated by Django 3.1 on 2020-08-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0012_twitchsettings_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchsettings',
            name='client_secret',
            field=models.SlugField(default='CHANGE THIS'),
        ),
        migrations.AlterField(
            model_name='twitchsettings',
            name='client_id',
            field=models.SlugField(default='CHANGE THIS'),
        ),
    ]
