# Generated by Django 3.1 on 2020-08-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0013_auto_20200814_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchsettings',
            name='broadcaster_name',
            field=models.SlugField(default='CHANGE THIS', max_length=30),
        ),
    ]
