# Generated by Django 3.1 on 2020-08-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0014_auto_20200814_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchsettings',
            name='broadcaster_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
