# Generated by Django 3.1 on 2020-08-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0015_auto_20200814_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchsettings',
            name='bearer',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitchsettings',
            name='broadcaster_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitchsettings',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
