# Generated by Django 3.1 on 2020-08-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0017_remove_twitchsettings_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clip',
            old_name='archived',
            new_name='clip_archived',
        ),
        migrations.AddField(
            model_name='clip',
            name='thumbnail_archived',
            field=models.BooleanField(default=False),
        ),
    ]
