# Generated by Django 3.1 on 2020-08-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0020_auto_20200815_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail_archived',
            field=models.BooleanField(default=False),
        ),
    ]
