# Generated by Django 3.1 on 2020-08-15 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0021_game_thumbnail_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='thumbnail_archived',
        ),
    ]
